return {
  { 'andymass/vim-matchup' },
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
      local configs = require('nvim-treesitter.configs')

      configs.setup({
        ensure_installed = {
          'bash',
          'c',
          'cmake',
          'comment',
          'commonlisp',
          'corn',
          'cpp',
          'css',
          'csv',
          'cuda',
          'diff',
          'dockerfile',
          'elixir',
          'fennel',
          'git_config',
          'git_rebase',
          'gitattributes',
          'gitcommit',
          'gitignore',
          'glsl',
          'go',
          'gomod',
          'gpg',
          'heex',
          'hjson',
          'html',
          'html',
          'http',
          'ini',
          'javascript',
          'jq',
          'jsdoc',
          'json',
          'json5',
          'llvm',
          'lua',
          'luadoc',
          'luap',
          'make',
          'markdown',
          'markdown_inline',
          'ninja',
          'nix',
          'norg',
          'passwd',
          'proto',
          'python',
          'query',
          'regex',
          'rst',
          'rust',
          'scss',
          'ssh_config',
          'terraform',
          'toml',
          'tsx',
          'typescript',
          'vim',
          'vimdoc',
          'wgsl',
          'yaml',
          'yuck',
          'zig',
        },
        sync_install = false,
        highlight = { enable = true },
        indent = { enable = true },
        matchup = { enable = true },
      })
    end,
  },
}
